builds:
  - main: main.go
    binary: orb-update
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
# Archive customization
archives:
  - format: tar.gz
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
    files:
      - LICENSE
      - README.md

brews:
  -
    name: orb-update
    github:
      owner: sawadashota
      name: homebrew-cheers
    commit_author:
      name: sawadashota
      email: xiootas@gmail.com
    homepage:  https://github.com/sawadashota/orb-update
    description: Update Orbs versions
    skip_upload: false
    test: |
      system "#{bin}/orb-update -h"
    install: |
      bin.install "orb-update"
