# target config file path
# default is `.circleci/config.yml`
file_path: .circleci/config.yml

repository:
  # name of this repository
  name: sawadashota/orb-update

git:
  # author of commit
  # require when Pull Request Creation
  # if empty, fetch from GitHub
  author:
    name: sawadashota
    email: example@example.com

github:
  # Pull Request creation option
  # default is false
  pull_request: false

  # these should be configured by environment variable because of credentials
  #
  # `GITHUB_USERNAME`
  #username: sawadashota
  # `GITHUB_TOKEN`
  #token: github_token

# base branch
# default is `master`
base_branch: master

filesystem:
  # filesystem strategy supports `os` and `memory`
  # default is `os` for easy to use in local
  # but in CI, `memory` is recommended
  strategy: os
