version: "3.7"

services:
  orb-update:
    build:
      context: "."
    environment:
      GITHUB_USERNAME: "${GITHUB_USERNAME}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
    volumes:
    - ".orb-update.yml:/orb-update/.orb-update.yml"
