version: 2.1

orbs:
  orb-update: sawadashota/orb-update@volatile
  docker: circleci/docker@0.5.20
  orb-tools: circleci/orb-tools@9.0.0
  envsubst: sawadashota/envsubst@1.1.0

executors:
  circleci-cli:
    docker:
      - image: circleci/circleci-cli:latest

jobs:
  test-go:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache:
          name: Restore go modules cache
          keys:
            - mod-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          name: Save go modules cache
          key: mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod/cache
      - run: go mod verify
      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: go tool cover -html coverage.txt -o coverage.html
      - run:
          name: Send result codecov
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
      - store_artifacts:
          path: coverage.html
          destination: coverage.html

  release-binary:
    docker:
      - image: goreleaser/goreleaser:v0.123
    steps:
      - checkout
      - run: go mod download
      - run: go mod verify
      - run: goreleaser

  pack-orb:
    environment:
      DOCKER_LATEST_TAG: latest
      ORB_LATEST_TAG: volatile
    parameters:
      docker_image_latest_tag:
        description: Latest docker image tag of orb-update
        type: env_var_name
        default: CIRCLE_TAG
      orb_latest_version:
        description: Latest orb version of orb-update
        type: env_var_name
        default: CIRCLE_TAG
    executor: circleci-cli
    steps:
      - checkout
      - attach_workspace:
          at: .
      - envsubst/install
      - run:
          name: Embed environment variables to orb.yml
          command: |
            ENVSUBST_ORB_UPDATE_DOCKER_TAG=${<< parameters.docker_image_latest_tag >>} \
              ENVSUBST_ORB_VERSION=${<< parameters.orb_latest_version >>} \
              envsubst < circleci-orb/src/@orb.template.yml > circleci-orb/src/@orb.yml
      - orb-tools/pack:
          destination: circleci-orb/packed/orb.yml
          source: circleci-orb/src/
      - orb-tools/validate:
          orb-path: circleci-orb/packed/orb.yml
      - persist_to_workspace:
          root: .
          paths:
            - circleci-orb/packed/orb.yml
      - store_artifacts:
          path: circleci-orb/packed/orb.yml
          destination: orb.yml

workflows:
  version: 2
  dev:
    jobs:
      - test-go
      - docker/publish:
          name: build-docker-image-dev
          deploy: false
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/hadolint:
          name: hadolint-dev
          # https://github.com/hadolint/hadolint/wiki/DL3018
          ignore-rules: DL3018
      - pack-orb:
          name: pack-orb-dev
          docker_image_latest_tag: DOCKER_LATEST_TAG
          orb_latest_version: ORB_LATEST_TAG
      - orb-tools/publish-dev:
          name: publish-orb-dev
          context: circleci
          requires:
            - pack-orb-dev
          orb-name: sawadashota/orb-update
          orb-path: circleci-orb/packed/orb.yml
          publish-token-variable: CIRCLE_TOKEN
          validate: true
          checkout: false
          attach-workspace: true
          workspace-root: .

  master:
    jobs:
      - docker/publish:
          name: publish-docker-image-master
          filters:
            branches:
              only: master
          deploy: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD

  release:
    jobs:
      - release-binary:
          filters: &release_filter
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - docker/publish:
          name: publish-docker-image
          filters: *release_filter
          deploy: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: ${CIRCLE_TAG}
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
      - pack-orb:
          name: pack-relase-orb
          filters: *release_filter
          docker_image_latest_tag: CIRCLE_TAG
          orb_latest_version: CIRCLE_TAG
      - orb-tools/publish:
          name: publish-orb
          filters: *release_filter
          context: circleci
          requires:
            - publish-docker-image
            - pack-relase-orb
          orb-ref: sawadashota/orb-update@${CIRCLE_TAG}
          orb-path: circleci-orb/packed/orb.yml
          publish-token-variable: CIRCLE_TOKEN
          validate: true
          checkout: false
          attach-workspace: true
          workspace-root: .

  orb-update:
    jobs:
      - orb-update/orb-update:
          context: orb-update
          name: daily-orb-update
          repository: sawadashota/orb-update
    triggers:
      - schedule:
          cron: "0 10 * * *"  # minute hour day month week (UTC)
          filters:
            branches:
              only:
                - master
