version: 2.1

orbs:
  docker: circleci/docker@0.5.18
  circleci-cli: circleci/circleci-cli@0.1.6
  orb-tools: circleci/orb-tools@8.27.6

jobs:
  test-go:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache:
          name: Restore go modules cache
          keys:
            - mod-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          name: Save go modules cache
          key: mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod/cache
      - run: go mod verify
      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: go tool cover -html coverage.txt -o coverage.html
      - run:
          name: Send result codecov
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
      - store_artifacts:
          path: coverage.html
          destination: coverage.html
  release-binary:
    docker:
      - image: goreleaser/goreleaser:v0.123
    steps:
      - checkout
      - run: go mod download
      - run: go mod verify
      - run: goreleaser
  pack-orb:
    executor: circleci-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - orb-tools/pack:
          destination: circleci-orb/packed/orb.yml
          source: circleci-orb/src/
      - orb-tools/validate:
          orb-path: circleci-orb/packed/orb.yml
      - persist_to_workspace:
          root: .
          paths:
            - circleci-orb/packed/orb.yml
      - store_artifacts:
          path: circleci-orb/packed/orb.yml
  orb-update:
    docker:
      - image: docker:19.03.5
    working_directory: /repo
    steps:
      - setup_remote_docker
      - run: docker pull sawadashota/orb-update:v0.0.3
      - run:
         name: Update Orbs
         command: |
           docker run --rm \
            -e GIT_USERNAME="${GIT_USERNAME}" \
            -e GIT_EMAIL="${GIT_EMAIL}" \
            -e GITHUB_USERNAME="${GITHUB_USERNAME}" \
            -e GITHUB_TOKEN="${GITHUB_TOKEN}" \
            -e TARGET_BRANCH="${TARGET_BRANCH}" \
            -e FILESYSTEM_STRATEGY=memory \
            sawadashota/orb-update:latest \
            orb-update -r $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:v0.0.3 --pull-request

workflows:
  version: 2
  test:
    jobs:
      - test-go
      - docker/publish:
          deploy: false
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/hadolint:
          # https://github.com/hadolint/hadolint/wiki/DL3018
          ignore-rules: DL3018
      - pack-orb
      - orb-tools/publish-dev:
          context: circleci
          requires:
            - pack-orb
          orb-name: sawadashota/orb-update
          orb-path: circleci-orb/packed/orb.yml
          publish-token-variable: CIRCLE_TOKEN
          validate: true
          checkout: false
          attach-workspace: true
          workspace-root: .

  release-master:
    jobs:
      - docker/publish:
          filters:
            branches:
              only: master
          deploy: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD

  release-version:
    jobs:
      - release-binary:
          filters: &release_filter
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - docker/publish:
          filters: *release_filter
          deploy: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: ${CIRCLE_TAG}
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
      - pack-orb:
          filters: *release_filter
      - orb-tools/publish:
          filters: *release_filter
          context: circleci
          requires:
            - docker/publish
            - pack-orb
          orb-ref: sawadashota/orb-update@${CIRCLE_TAG}
          orb-path: circleci-orb/packed/orb.yml
          publish-token-variable: CIRCLE_TOKEN
          validate: true
          checkout: false
          attach-workspace: true
          workspace-root: .

  self-orb-update:
    jobs:
      - orb-update
    triggers:
      - schedule:
          cron: "0 10 * * *"  # minute hour day month week (UTC)
          filters:
            branches:
              only:
                - master
