#
# Orb template file
#
# Before packing, replace ENVSUBST_ prefix texts by envsubst command
# https://github.com/a8m/envsubst
#

version: 2.1

description: |
  Update CircleCI Orbs versions
  https://github.com/sawadashota/orb-update

executors:
  docker:
    docker:
      - image: docker:19.03.5
commands:
  orb-update:
    description: >
      Execute orb-update command via docker command.
      Update each Orb version and create Pull Request on GitHub.
    parameters: &parameters
      base_branch:
        description: Base branch name of Pull Request
        type: string
        default: master
      repository:
        description: Repository name to update Orb ex) sawadashota/orb-update
        type: string
      github_username:
        description: Username of GitHub Token's owner
        type: env_var_name
        default: GITHUB_USERNAME
      github_token:
        description: |
          GitHub Token to read/create Pull Request
          https://github.com/settings/tokens/new?scopes=repo&description=Octotree%20browser%20extension
        type: env_var_name
        default: GITHUB_TOKEN
      git_author_user:
        description: Name for commit signature
        type: env_var_name
        default: GIT_AUTHOR_NAME
      git_author_email:
        description: Email for commit signature
        type: env_var_name
        default: GIT_AUTHOR_EMAIL
      docker_image_version:
        description: |
          Version of docker image sawadashota/orb-update
          https://hub.docker.com/r/sawadashota/orb-update
        type: string
        default: ${ENVSUBST_ORB_UPDATE_DOCKER_TAG} # will be replaced by envsubst
    steps:
      - run: docker pull sawadashota/orb-update:<< parameters.docker_image_version >>
      - run:
          name: Update Orbs
          command: |
            docker run --rm \
             -e BASE_BRANCH="<< parameters.base_branch >>" \
             -e GITHUB_USERNAME="${<< parameters.github_username >>}" \
             -e GITHUB_TOKEN="${<< parameters.github_token >>}" \
             -e GIT_AUTHOR_NAME="$<< parameters.git_author_user >>" \
             -e GIT_AUTHOR_EMAIL="${<< parameters.git_author_email >>}" \
             -e FILESYSTEM_STRATEGY=memory \
             sawadashota/orb-update:<< parameters.docker_image_version >> \
             orb-update -r "<< parameters.repository >>" --pull-request
jobs:
  orb-update:
    description: >
      Execute orb-update command.
      Update each Orb version and create Pull Request on GitHub.
    executor: docker
    parameters: *parameters
    steps:
      - setup_remote_docker
      - orb-update:
          base_branch: << parameters.base_branch >>
          repository: << parameters.repository >>
          github_username: << parameters.github_username >>
          github_token: << parameters.github_token >>
          git_author_user: << parameters.git_author_user >>
          git_author_email: << parameters.git_author_email >>
          docker_image_version: << parameters.docker_image_version >>

examples:
  update-every-night:
    description: |
      Check and update orb every night.
    usage:
      orbs:
        orb-update: sawadashota/orb-update@${ENVSUBST_ORB_VERSION} # will be replaced by envsubst
      version: 2.1
      workflows:
        orb-update:
          jobs:
            - orb-update/orb-update:
                repository: sawadashota/orb-update
          triggers:
            - schedule:
                cron: "0 19 * * *"
                filters:
                  branches:
                    only:
                      - master
